# Conexion mysql
spring.datasource.url = jdbc:mysql://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Evitar que se cree el esquema de bd
spting.jpa.hibernate.ddl-auto=none
#Yo coloque true y es por l que veo el detalle de hibernate
spring.jpa.show-sql=false
# Tema de primefaces por default tema saga, claro
joinfaces.primefaces.theme=vela
